const $=s=>document.querySelector(s);
async function load(){
 const [summary,series,routeData]=await Promise.all([fetch('data/summary.json').then(r=>r.json()),fetch('data/series.json').then(r=>r.json()),fetch('data/route.json').then(r=>r.json())]);
 $('#device').textContent=`${summary.device} / iOS ${summary.os}`;$('#period').textContent=`${summary.start} → ${summary.end}`;
 const cards=[['記録時間',`${summary.duration_min} 分`,`${summary.location_samples} location points`],['移動距離',`${(summary.distance_m/1000).toFixed(2)} km`,'位置データから算出'],['平均速度',`${summary.speed_mean_mps.toFixed(2)} m/s`,`${(summary.speed_mean_mps*3.6).toFixed(1)} km/h`],['気圧変化',`${summary.pressure_change_hpa>=0?'+':''}${summary.pressure_change_hpa} hPa`,`${summary.pressure_min_hpa}–${summary.pressure_max_hpa} hPa`]];
 $('#cards').innerHTML=cards.map(c=>`<div class="card"><div class="label">${c[0]}</div><div class="value">${c[1]}</div><div class="sub">${c[2]}</div></div>`).join('');
 drawRoute(routeData.route);drawChart('pressureChart',series.pressure,'hPa');drawChart('speedChart',series.speed,'m/s');drawChart('heightChart',series.height,'m');
 const pd=summary.pressure_max_hpa-summary.pressure_min_hpa;$('#analysis').innerHTML=[['最高速度',`${summary.speed_max_mps.toFixed(2)} m/s（${(summary.speed_max_mps*3.6).toFixed(1)} km/h）`],['高度レンジ',`${summary.height_min_m}–${summary.height_max_m} m（差 ${Math.abs(summary.height_max_m-summary.height_min_m).toFixed(1)} m）`],['気圧レンジ',`${summary.pressure_min_hpa}–${summary.pressure_max_hpa} hPa（幅 ${pd.toFixed(3)} hPa）`],['取得サンプル',`気圧 ${summary.barometer_samples} 点 / 位置 ${summary.location_samples} 点`]].map(x=>`<div class="analysis-row"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
}
function drawRoute(route){const svg=$('#routeMap'),W=700,H=420,p=70;const xs=route.map(r=>r.x),ys=route.map(r=>r.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const sx=(W-2*p)/(maxX-minX||1),sy=(H-2*p)/(maxY-minY||1),s=Math.min(sx,sy);const ox=(W-(maxX-minX)*s)/2,oy=(H-(maxY-minY)*s)/2;const pts=route.map(r=>`${ox+(r.x-minX)*s},${H-(oy+(r.y-minY)*s)}`).join(' ');let g='';for(let x=20;x<W;x+=50)g+=`<line x1="${x}" y1="0" x2="${x}" y2="${H}" class="grid"/>`;for(let y=20;y<H;y+=50)g+=`<line x1="0" y1="${y}" x2="${W}" y2="${y}" class="grid"/>`;svg.innerHTML=`${g}<polyline points="${pts}" class="route-line"/><text x="18" y="30" class="map-label">ANONYMIZED ROUTE</text>`}
function drawChart(id,data,unit){const c=document.getElementById(id),dpr=devicePixelRatio||1,r=c.getBoundingClientRect(),w=Math.max(320,r.width),h=+c.height;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const pad={l:46,r:16,t:16,b:30},xs=data.map(p=>p.t),ys=data.map(p=>p.v),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),yr=ymax-ymin||1,x=t=>pad.l+(t-xmin)/(xmax-xmin||1)*(w-pad.l-pad.r),y=v=>h-pad.b-(v-ymin)/yr*(h-pad.t-pad.b);ctx.font='11px -apple-system,sans-serif';ctx.strokeStyle='#e8ecf0';ctx.fillStyle='#7a8590';for(let i=0;i<4;i++){const yy=pad.t+i*(h-pad.t-pad.b)/3;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillText((ymax-(ymax-ymin)*i/3).toFixed(unit==='hPa'?2:1),6,yy+4)}ctx.fillText(`${xmin.toFixed(0)}s`,pad.l,h-8);ctx.fillText(`${xmax.toFixed(0)}s`,w-pad.r-32,h-8);ctx.beginPath();data.forEach((p,i)=>{const xx=x(p.t),yy=y(p.v);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.strokeStyle='#1f2937';ctx.lineWidth=2;ctx.stroke()}
load().catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend','<p style="padding:20px">データの読み込みに失敗しました。GitHub PagesなどHTTP環境で開いてください。</p>')});
